name: CI
on:
  push:
    branches: ['main']
jobs:
  build-scp:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: install node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.X'

    - name: enable corepack
      run: corepack enable
      
    - name: install deps
      run: pnpm i
      
    - name: build app
      run: pnpm build
      
      
    - name: scp Files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }},
        username: ${{ secrets.REMOTE_USERNAME }},
        password: ${{ secrets.REMOTE_PASSWORD }},
        port: 22
        source: 'dist/'
        target: ${{ secrets.REMOTE_TARGET }}
        command_timeout: 2m
